### ISSUE TITLE
Door / Entrance Ambiguity

### ISSUE THREAD

**Issue by Bartholomue** [Croutonic-Creations/SDV-AccessibleTiles#54]
Consider renaming the entrance category to "Areas" so that it's very obvious that this category is listing the entrances to connected areas. I noticed people can be confused between door and entrance categories, synce the two terms are synonymous.

**Comment by GrumpyCrouton** [comment]
I don't think they are synonymous, because a door is not necessarily an entrance.

I like entrance because it's an entrance to an area. Areas is confusing to me because an area may have multiple entrances, and that would make it seem like there is multiple of a single area.

I will concede that both names are a bit confusing but I think entrances is less so.

I'm willing to change it if we can find a better name. Closing for now
